

pipeline {
    agent {
        docker {
            image 'node:lts-bullseye-slim' 
            args '-p 3000:3000' 
            label "docker"
        }
    }
    stages {
        stage('Build') { 
            steps {
                sh 'chown -R jenkins ~/.npm'
                sh 'npm install' 
            }
        }
    }
}

